name: Create torrent using mktorrent
on:
  push:
    paths:
      - ".github/workflows/mktorrent.yml"
      
env:
  name: "my hero"
  comment: "yo"
  url: "https://download165.uploadhaven.com/1/application/zip/zm4kRzwElbLq6KmNH3zzJVhGSI5bNcM8Jydy8k4x.zip?key=FH3AzLiHDFxkhPBrbIiwWA&expire=1627450883&filename=My.Hero.Ones.Justice.2.ALL.DLCs.zip"
  file_name: "my hero one"
  piece_size: 2 # Check the README.md for recommended piece size
  maximize_disk_space: false # Set to true if out of disk space
  
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Maximize disk space
        if: ${{ env.maximize_disk_space == 'true' }}
        uses: easimon/maximize-build-space@v4
        with:
          remove-dotnet: 'true'
          remove-android: 'true'
          remove-haskell: 'true'
          
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: aria2c -x 16 -o "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name" # Tested on v1.1
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent